organizar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'organizar.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

apps/_accounting/models.py
# coding=UTF-8

from django.db import models
import datetime
from datetime import timedelta
from django.contrib.auth.models import User
from calendar import monthrange
import traceback
import sys 
from apps._person.models import Person

DUN_LEVEL = (
	('1', 'First'),
	('2', 'Second'),
	('3', 'Third'),
)

ACCOUNT_TYPE = (
	('activa', 'Activa'),
	('passiva', 'Passiva'),
)

class Amount(models.Model):
	amount = models.IntegerField(max_length=1)

	def __unicode__(self):
		return str(self.amount)

	class Meta:
		verbose_name = "Teilnamehäufigkeit"
		verbose_name_plural = "Teilnamehäufigkeiten"

class Duration(models.Model):
	duration = models.DecimalField("Dauer / Minuten", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return str(self.duration)

	class Meta:
		verbose_name = "Dauer"
		verbose_name_plural = "Dauer"


class Product(models.Model):
	name = models.CharField(max_length=200)
	charge = models.DecimalField("Kosten / Stunde", max_digits=5, decimal_places=2, blank=True, null=True)
	duration = models.OneToOneField(Duration, default=1)
	amount = models.OneToOneField(Amount, default=1)
	months = models.IntegerField(max_length=2, blank=True, null=True)
	days_a_week = models.IntegerField(max_length=1, blank=True, null=True)

	def __unicode__(self):
		return u'%s' % (self.charge)

	class Meta:
		verbose_name = "Produkt"
		verbose_name_plural = "Produkte"


class Discount(models.Model):
	discount = models.CharField("Rabatt", max_length=200)
	name = models.CharField("Name", max_length=200)

	def __unicode__(self):
		return str(self.name) + " " + str(self.discount) + "%"

	class Meta:
		verbose_name = "Rabatt"
		verbose_name_plural = "Rabatte"


class Contract(models.Model):
	number = models.CharField("Vertragsnummer", max_length=200)
	products =models.ManyToManyField(Product, blank=True, null=True, related_name='products')
	start_date = models.DateField("Start Date", default=datetime.date.today)
	end_date = models.DateField("End Date", default=datetime.date.today)
	#charge = models.ForeignKey(Charge)
	contact = models.OneToOneField(User,related_name='contract_contact')
	billing_contact = models.OneToOneField(User,related_name='contract_billing_contact')
	#duration = models.ForeignKey(Duration)
	#frequency = models.ForeignKey(Frequency)
	discount = models.ManyToManyField(Discount, blank=True, null=True, related_name='contract_discounts')

	def __unicode__(self):
		return self.number

	def get_frequency_per_week(self):
		return self.type.frequency.frequency / 4

	def calc_price(self):
		x = None

		try:
			x = float(self.type.frequency.frequency) * float(self.type.charge.charge)
		except:
			traceback.print_exc(file=sys.stdout)

		return float(x)

	def get_discounts(self):
		discounts = []
		try:
			x = self.calc_price()

			if x != None:
				for discount in self.discount.all():	
					discount_data = {}
					d = x * (float(discount.discount)/100)
					discount_data["amount"] = float(d)
					discount_data["name"] = discount.name
					discount_data["discount"] = discount.discount
					discounts.append(discount_data)
		except:
			traceback.print_exc(file=sys.stdout)	

		return discounts


	def calc_summ(self):
		summ = None
		registration_fee = 39

		try:
			summ = self.calc_price() + registration_fee
			discounts = self.get_discounts()

			for discount in discounts:
				summ = summ - discount["amount"]
		except:
			traceback.print_exc(file=sys.stdout)	

		return summ
	
	def calc_summ_without_fee(self):
		registration_fee = 39
		summ = self.calc_summ()
		summ = summ - registration_fee

		return summ

	def calc_month_difference(self):
		d1 = self.start_date
		d2 = self.end_date 
		delta = 0

		while True:
			mdays = monthrange(d1.year, d1.month)[1]
			d1 += timedelta(days=mdays)
			if d1 <= d2:
				delta += 1
			else:
				break

		return delta

	class Meta:
		verbose_name = "Vertrag"
		verbose_name_plural = "Verträge"

# Mahnung
class Dun(models.Model):
	level = models.CharField("Mahnlevel", max_length=1, choices=DUN_LEVEL, default=1)


class Invoice(models.Model):
	number = models.CharField("Rechnungsnummer", max_length=200)
	contract = models.OneToOneField(Contract)
	date = models.DateField()
	payed = models.BooleanField()
	dun = models.OneToOneField(Dun)

	def __unicode__(self):
		return (str(self.number) + " " + str(self.person.name))
	
	class Meta:
		verbose_name = "Rechnung"
		verbose_name_plural = "Rechnungen"

class Account(models.Model):
	name = models.CharField("Konto", max_length=200)
	type = models.CharField("Typ", max_length=1, choices=ACCOUNT_TYPE, blank=True, null=True)
	balance = models.DecimalField("Saldo", max_digits=5, decimal_places=2, blank=True, null=True)
	
	def __unicode__(self):
		return (str(self.name) + " " + str(self.balance))
	
class Account_Record(models.Model):
	amount = models.DecimalField("€", max_digits=5, decimal_places=2, blank=True, null=True)
	asset = models.OneToOneField(Account)
	liability = models.OneToOneField(Account)
	date = models.DateField()

	def __unicode__(self):
		return (str(self.liability.name) + " / " + str(self.asset.name) + " " + str(self.amount) + "€")
	

apps/_person/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

SEX = (
	('m', 'Herr'),
	('f', 'Frau'),
)


class Subject(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Fach"
		verbose_name_plural = "Fächer"

class Grade(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Klasse"
		verbose_name_plural = "Klassen"

class School(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Schule"
		verbose_name_plural = "Schulen"


# TODO find better naming 
class Child_Contact(models.Model):
	grade = models.OneToOneField(Grade, blank=True, null=True) # new
	school = models.OneToOneField(School, blank=True, null=True) # new

	def __unicode__(self):
		return self.child.street

	class Meta:
		verbose_name = "Schüler"
		verbose_name_plural = "Schüler"

class Billing_Type(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Rechnungstyp"
		verbose_name_plural = "Rechnungstypen"

class Billing_Contact(models.Model):
	knr = models.CharField(max_length=200, blank=True, null=True)
	blz = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	billing_type = models.OneToOneField(Billing_Type, blank=True, null=True)

	def __unicode__(self):
		return self.person.user.last_name

	class Meta:
		verbose_name = "Rechnungsadresse"
		verbose_name_plural = "Rechnungsadressen"

class Person(models.Model):
	sex = models.CharField("Geschlecht", max_length=1, choices=SEX, blank=True, null=True)
	birthday = models.DateField("Geburtstag", blank=True, null=True) # new
	street = models.CharField("Strasse", max_length=200, blank=True, null=True)
	hnr = models.CharField("Hausnummer", max_length=10, blank=True, null=True)
	zip = models.IntegerField("PLZ", max_length=8, blank=True, null=True)
	city = models.CharField("Stadt", max_length=200, blank=True, null=True)
	country = models.CharField("Land", max_length=200, blank=True, null=True) # new
	phone = models.CharField("Telefon", max_length=200, blank=True, null=True)
	mobile = models.CharField("Handy", max_length=200, blank=True, null=True)
	accessibility = models.CharField("Mögliche Termine oder Zeiten wo unmöglich gehen.", max_length=600, blank=True, null=True) # new
	user = models.OneToOneField(User)
	child_contact = models.OneToOneField(Child_Contact)
	billing_contact = models.OneToOneField(Billing_Contact)

	def __unicode__(self):
		return str(self.mobile)
	
	def get_user(self):
		return self.user

	class Meta:
		verbose_name = "Benutzer"
		verbose_name_plural = "Benutzer"

templates/base/base.html
{% include "base/header.html" %}

<body>
	{% block content %}
		content
	{% endblock %}
</body>

{% include "base/footer.html" %}

templates/base/footer.html
	<footer>
		{% block footer %}
		{% endblock %}
	</footer>
</html>)

templates/base/header.html
{% load i18n admin_modify staticfiles %}

<!DOCTYPE html>

<html lang="de">
	<head>
		<meta charset="utf-8" />
		
		<title>Schüler Verwaltung</title>
		
		<link rel="stylesheet" type="text/css" href="/media/css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="/media/css/foundation.min.css" />
		<link rel="stylesheet" type="text/css" href="/media/css/core.css" />
	
		<style>
			.pace .pace-progress {
				background: #29d;
				position: fixed;
				z-index: 2000;
				bottom: 0;
				left: 0;
				height: 10px;
			
				-webkit-transition: width 1s;
				-moz-transition: width 1s;
				-o-transition: width 1s;
				transition: width 1s;
			}
	
			.pace-inactive {
				display: none;
			}
			.pace .pace-progress:after {
				display: block;
				position: fixed;
				bottom: 30px;
				left: .5rem;
				content: attr(data-progress-text);
				font-family: "Helvetica Neue", sans-serif;
				font-weight: 100;
				font-size: 1em;
				line-height: 1em;
				text-align: right;
				color: rgba(0, 0, 0, 0.79999999999999996);
			}
		</style>
	
		<script type="text/javascript" src="/media/js/lib/jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="/media/js/lib/jquery-ui-1.10.2.custom.min.js"></script>
		<script type="text/javascript" src="/media/js/lib/mustache.js"></script>
		<script type="text/javascript" src="/media/js/lib/jquery.cookie.js"></script>
		<script type="text/javascript" src="/media/js/lib/pace.js"></script>
		<script type='text/javascript' src="/media/js/lib/jquery.maskedinput.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="/media/js/lib/bootstrap.js"></script>
		<script type='text/javascript' src='/media/js/lib/jquery.mousewheel.min.js'></script>
		
		<script type="text/javascript" src="/media/js/globals.js"></script>
		<script type="text/javascript" src="/media/js/slider.js"></script>
		<script type="text/javascript" src="/media/js/module.overlay.js"></script>
		<script type="text/javascript" src="/media/js/module.infobox.js"></script>
	
		<script>	
			var ALL_EVENTS = null; /*{% if json_events %}{% autoescape off %}{{ json_events }}{% endautoescape %}{% else %}null{% endif %};*/
			var csrf_token = "{{csrf_token}}";
			var SHOW_EVENTS = {% if show_events %}true{% else %}false{% endif %};
		</script>
	
		<script type="text/javascript" src="/media/js/utils/date_util.js"></script>
		<script type="text/javascript" src="/media/js/models/autocomplete.js"></script>
		<script type="text/javascript" src="/media/js/models/calendar_model.js"></script>
		<script type="text/javascript" src="/media/js/models/user_search_model.js"></script>
		<script type="text/javascript" src="/media/js/models/ajax_model.js"></script>
		<script type="text/javascript" src="/media/js/models/todo_model.js"></script>
		<script type="text/javascript" src="/media/js/models/menu_model.js"></script>
		<script type="text/javascript" src="/media/js/views/calendar_view.js"></script>
		<script type="text/javascript" src="/media/js/module.infobox.js"></script>
		<script type="text/javascript" src="/media/js/module.buttonEvents.js"></script>
	
	
		<script>
			function handle_contract() {
				var add_user_buttons = $("#add-new-contact, #add-new-billing-contact");
	
				add_user_buttons.click(function() {
					var button = $(this);
					var wrapper = $(this).parent();
	
					button.addClass("hidden");
					wrapper.find(".new-user-form").removeClass("hidden");
					wrapper.find(".user-search").addClass("hidden");
	
					wrapper.find(".back").click(function() {
						button.removeClass("hidden");
						wrapper.find(".new-user-form").addClass("hidden");
						wrapper.find(".user-search").removeClass("hidden");
					});
				});
			
				// show contract id if existing
				var contract_id_field = $("#id_number");
				var contract_id = contract_id_field.val();
				if (typeof contract_id != "undefined" && contract_id != "") {
					contract_id_field.parent().prepend(contract_id);
				}
			
				// show and set billing contact if recently created
	// 			var user_id = $("#id_id").attr("value");
	// 			if (typeof user_id != "undefined" && user_id != "") {
	// 				var select_options = $("#id_billing_contact").find("option");
	// 				select_options.attr('selected', false);
	// 				$.each(select_options, function(key, option) {
	// 					var option = $(option);
	// 					var value = option.val();
	// 					if (value == user_id) {
	// 						var wrapper = option.parent().parent();
	// 						option.attr('selected', true);
	// 						//wrapper.css("display", "block");
	// 						//wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");
	// 						//wrapper.prepend("<label>Rechnungsadresse:</label><input type=\"text\" value=\"" + option.text() + "\"readonly=\"readonly\"/>");
	
	// 						return false;
	// 					}
	// 				});
	// 			}
			
				var selected_billing_options = $("#id_billing_contact").find("option:selected");
				show_select_option(selected_billing_options, null, "Vertragspartner", 'id_billing_contact');
	
				// show contact if set 
				var selected_options = $("#id_contact").find("option:selected");
				show_select_option(selected_options, null, "Schüler", 'id_contact');
	
				function show_select_option(selected_options, value, label, id) {
					$.each(selected_options, function(key, option) {
						var option = $(option);
						var wrapper = option.parent().parent();
						var text = "";
						var newID = "target_" + id
						var errorDiv = wrapper.find(".error");
	
						wrapper.css("display", "block");
						wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");
	
						if (typeof value != "undefined" && value != null && value != "") {
							text = value;
						}
						else {
							if (option.text() != "---------") {
								text = option.text();
								$.cookie(id, text);
							}
						}
						wrapper.prepend(errorDiv[0].outerHTML + "<label>" + label + ":</label><input id=\"" + newID + "\" type=\"text\" value=\"" + text + "\"readonly=\"readonly\"/>");
					});
				}
			}
	
			/**
			 *
			 * FUNCTION handlePrint
			 *
			 */
			function handlePrint() {
				var contract_type = $("#contract-type");
	
				if (typeof contract_type != "undefined") {
					var text = contract_type.text();
					text = text.split(" - ")[0];
					contract_type.text(text);
				}
	
				handlePagebreaks();
	
				function handlePagebreaks() {
					var events = $(".events");
					$.each(events, function(key, event_list) {
						var height = 0;
						var event_list = $(event_list).find(".event");
						$.each(event_list, function(key, event){
							var event = $(event);
							height = height + parseInt(event.height());
							if (height > 700) {
								event.prepend('<div class="new-page"></div>');
								height = 0;
							}
						});
					});
				}
	
				var d1 = new Date();
				var d = d1.getDate();
				var m = d1.getMonth() + 1;
				var y = d1.getFullYear();
				var dateField = Overlay.SELF.find("#date");
				var temp = new Date();
				var dateStr = "";
				console.log("Overlay.SELF " , Overlay.SELF);
				console.log("~~~ DATE FIELD " + dateField.size(), dateField);
				console.log("~~~ 0");
				d1 = Date_Util.dateToYMD(d1);
				console.log("~~~ 1");
				dateField.mask("99.99.9999", {reverse: true});
				console.log("~~~ 2");
				dateStr = Date_Util.dateToYMD(temp);
				console.log("~~~ 3");
				console.log("~~~ DATE STRING ", dateStr);
				dateField.attr("value",dateStr);
			}
		</script>
	</head>	

templates/base/header_small.html
{% load i18n admin_modify staticfiles %}

<!DOCTYPE html>

<html lang="de">
<head>
	<meta charset="utf-8" />
	
	<title>Schüler Verwaltung</title>
	
	<link rel="stylesheet" type="text/css" href="/media/css/normalize.css" />
	<link rel="stylesheet" type="text/css" href="/media/css/foundation.min.css" />
	<link rel="stylesheet" type="text/css" href="/media/css/core.css" />

	<style>
		.pace .pace-progress {
			background: #29d;
			position: fixed;
			z-index: 2000;
			bottom: 0;
			left: 0;
			height: 10px;
		
			-webkit-transition: width 1s;
			-moz-transition: width 1s;
			-o-transition: width 1s;
			transition: width 1s;
		}

		.pace-inactive {
			display: none;
		}
		.pace .pace-progress:after {
			display: block;
			position: fixed;
			bottom: 30px;
			left: .5rem;
			content: attr(data-progress-text);
			font-family: "Helvetica Neue", sans-serif;
			font-weight: 100;
			font-size: 1em;
			line-height: 1em;
			text-align: right;
			color: rgba(0, 0, 0, 0.79999999999999996);
		}
	</style>

	<script type="text/javascript" src="/media/js/lib/jquery-1.8.2.min.js"></script>
	<script type="text/javascript" src="/media/js/lib/jquery-ui-1.10.2.custom.min.js"></script>
	<script type="text/javascript" src="/media/js/lib/mustache.js"></script>
	<script type="text/javascript" src="/media/js/lib/jquery.cookie.js"></script>
	<script type="text/javascript" src="/media/js/lib/pace.js"></script>
	<script type='text/javascript' src="/media/js/lib/jquery.maskedinput.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="/media/js/lib/bootstrap.js"></script>
	<script type='text/javascript' src='/media/js/lib/jquery.mousewheel.min.js'></script>
	
	<script type="text/javascript" src="/media/js/globals.js"></script>
	<script type="text/javascript" src="/media/js/slider.js"></script>
	<script type="text/javascript" src="/media/js/module.overlay.js"></script>
	<script type="text/javascript" src="/media/js/module.infobox.js"></script>

	<script>	
		var ALL_EVENTS = null; /*{% if json_events %}{% autoescape off %}{{ json_events }}{% endautoescape %}{% else %}null{% endif %};*/
		var csrf_token = "{{csrf_token}}";
		var SHOW_EVENTS = {% if show_events %}true{% else %}false{% endif %};
	</script>

	<script type="text/javascript" src="/media/js/utils/date_util.js"></script>
	<script type="text/javascript" src="/media/js/models/autocomplete.js"></script>
	<script type="text/javascript" src="/media/js/models/calendar_model.js"></script>
	<script type="text/javascript" src="/media/js/models/user_search_model.js"></script>
	<script type="text/javascript" src="/media/js/models/ajax_model.js"></script>
	<script type="text/javascript" src="/media/js/models/todo_model.js"></script>
	<script type="text/javascript" src="/media/js/models/menu_model.js"></script>
	<script type="text/javascript" src="/media/js/views/calendar_view.js"></script>
	<script type="text/javascript" src="/media/js/module.infobox.js"></script>
	<script type="text/javascript" src="/media/js/module.buttonEvents.js"></script>


	<script>
		function handle_contract() {
			var add_user_buttons = $("#add-new-contact, #add-new-billing-contact");

			add_user_buttons.click(function() {
				var button = $(this);
				var wrapper = $(this).parent();

				button.addClass("hidden");
				wrapper.find(".new-user-form").removeClass("hidden");
				wrapper.find(".user-search").addClass("hidden");

				wrapper.find(".back").click(function() {
					button.removeClass("hidden");
					wrapper.find(".new-user-form").addClass("hidden");
					wrapper.find(".user-search").removeClass("hidden");
				});
			});
		
			// show contract id if existing
			var contract_id_field = $("#id_number");
			var contract_id = contract_id_field.val();
			if (typeof contract_id != "undefined" && contract_id != "") {
				contract_id_field.parent().prepend(contract_id);
			}
		
			// show and set billing contact if recently created
// 			var user_id = $("#id_id").attr("value");
// 			if (typeof user_id != "undefined" && user_id != "") {
// 				var select_options = $("#id_billing_contact").find("option");
// 				select_options.attr('selected', false);
// 				$.each(select_options, function(key, option) {
// 					var option = $(option);
// 					var value = option.val();
// 					if (value == user_id) {
// 						var wrapper = option.parent().parent();
// 						option.attr('selected', true);
// 						//wrapper.css("display", "block");
// 						//wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");
// 						//wrapper.prepend("<label>Rechnungsadresse:</label><input type=\"text\" value=\"" + option.text() + "\"readonly=\"readonly\"/>");

// 						return false;
// 					}
// 				});
// 			}
		
			var selected_billing_options = $("#id_billing_contact").find("option:selected");
			show_select_option(selected_billing_options, null, "Vertragspartner", 'id_billing_contact');

			// show contact if set 
			var selected_options = $("#id_contact").find("option:selected");
			show_select_option(selected_options, null, "Schüler", 'id_contact');

			function show_select_option(selected_options, value, label, id) {
				$.each(selected_options, function(key, option) {
					var option = $(option);
					var wrapper = option.parent().parent();
					var text = "";
					var newID = "target_" + id
					var errorDiv = wrapper.find(".error");

					wrapper.css("display", "block");
					wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");

					if (typeof value != "undefined" && value != null && value != "") {
						text = value;
					}
					else {
						if (option.text() != "---------") {
							text = option.text();
							$.cookie(id, text);
						}
					}
					wrapper.prepend(errorDiv[0].outerHTML + "<label>" + label + ":</label><input id=\"" + newID + "\" type=\"text\" value=\"" + text + "\"readonly=\"readonly\"/>");
				});
			}
		}

		/**
		 *
		 * FUNCTION handlePrint
		 *
		 */
		function handlePrint() {
			var contract_type = $("#contract-type");

			if (typeof contract_type != "undefined") {
				var text = contract_type.text();
				text = text.split(" - ")[0];
				contract_type.text(text);
			}

			handlePagebreaks();

			function handlePagebreaks() {
				var events = $(".events");
				$.each(events, function(key, event_list) {
					var height = 0;
					var event_list = $(event_list).find(".event");
					$.each(event_list, function(key, event){
						var event = $(event);
						height = height + parseInt(event.height());
						if (height > 700) {
							event.prepend('<div class="new-page"></div>');
							height = 0;
						}
					});
				});
			}

			var d1 = new Date();
			var d = d1.getDate();
			var m = d1.getMonth() + 1;
			var y = d1.getFullYear();
			var dateField = Overlay.SELF.find("#date");
			var temp = new Date();
			var dateStr = "";
			console.log("Overlay.SELF " , Overlay.SELF);
			console.log("~~~ DATE FIELD " + dateField.size(), dateField);
			console.log("~~~ 0");
			d1 = Date_Util.dateToYMD(d1);
			console.log("~~~ 1");
			dateField.mask("99.99.9999", {reverse: true});
			console.log("~~~ 2");
			dateStr = Date_Util.dateToYMD(temp);
			console.log("~~~ 3");
			console.log("~~~ DATE STRING ", dateStr);
			dateField.attr("value",dateStr);
		}
	</script>
</head>

templates/base/print-old.html
<!-- 
<body>
	<section id="print">
			<div class="box">
				<h3>Stunden drucken</h3>
				<p>Geben Sie hier den Tag an von welchem Sie die Stunden drucken möchten.</p>
				<p>Nach dem Absenden ("klick" auf Termine anzeigen) ganz normal auf Drucken klicken oder "Strg" + "d" drücken.</p>
				<p></p>
				<p></p>
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="form-field">
						<label for="date">Datum</label><input type="text" id="date" name="date" />
						<input type="submit" value="Termine anzeigen">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Schüler Liste drucken</h3>
				<p></p>
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="form-field">
						<input type="hidden" name="print-users" value="True" />
						<input type="submit" value="Schüler Liste anzeigen">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Vertrag drucken</h3>
				<p></p>
	
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="search">
						<div class="form-field">
							<input id="trigger-contract-search" type="text" value="Suche" style="padding: 3px;" />
							<div id="contract-search-results" class="search-results"></div>
							<div id="contract-search-values" class="search-values">
								{% for contract in contracts %}
									<div data-type="{{ contract.type }}" data-id="{{ contract.pk }}" draggable="true" class="search-value contract button">
										VNr: {{ contract.number }}<br/>
										Person: {{ contract.contact.first_name }} {{  contract.contact.last_name }} <br/>
										Vertragsart: {{ contract.type }}<br/>
										Zeit: {{ contract.start_date }} bis {{ contract.end_date }}<br/>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
					{% if contracts %}
						<div class="form-field">
							<select id="id_contract" name="id_contract">
								<option value="">----------------------</option>
								{% for contract in contracts %}
									<option value="{{ contract.pk }}">{% if contract.number %}{{ contract.number }}{% endif %}{{ contract.contact.first_name }} {{  contract.contact.last_name }}</option>
								{% endfor %}
							</select>
						</div>
					{% endif %}
					<br/>
					<div class="form-field">
						<input type="hidden" name="print-contract" value="True" />
						<input type="submit" value="Vertrag drucken">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Stundenplan drucken</h3>
				<p></p>
	
				<form action="./" method="post">
					<div class="form-field">
						{% csrf_token %}
						{% if users %}
							Benutzer: 
							<select name="user">
							{% for user in users %}
								<option value="{{user.id}}">{{ user.username }}</option>
							{% endfor %}
							</select>
						{% endif %}
						<br/>
						<input type="hidden" name="print-calendar" value="True" />
						<input type="submit" value="Stundenplan anzeigen">
					</div>
				</form>
			</div>
	</section>
</body>
</html>
 -->