organizar/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'organizar.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

apps/_accounting/models.py
# coding=UTF-8

from django.db import models
import datetime
from datetime import timedelta
from django.contrib.auth.models import User
from calendar import monthrange
import traceback
import sys 
from apps._person.models import Person

DUN_LEVEL = (
	('1', 'First'),
	('2', 'Second'),
	('3', 'Third'),
)

ACCOUNT_TYPE = (
	('activa', 'Activa'),
	('passiva', 'Passiva'),
)

class Amount(models.Model):
	amount = models.IntegerField(max_length=1)

	def __unicode__(self):
		return str(self.amount)

	class Meta:
		verbose_name = "Teilnamehäufigkeit"
		verbose_name_plural = "Teilnamehäufigkeiten"

class Duration(models.Model):
	duration = models.DecimalField("Dauer / Minuten", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return str(self.duration)

	class Meta:
		verbose_name = "Dauer"
		verbose_name_plural = "Dauer"


class Product(models.Model):
	name = models.CharField(max_length=200)
	charge = models.DecimalField("Kosten / Stunde", max_digits=5, decimal_places=2, blank=True, null=True)
	duration = models.OneToOneField(Duration, default=1)
	amount = models.OneToOneField(Amount, default=1)
	months = models.IntegerField(max_length=2, blank=True, null=True)
	days_a_week = models.IntegerField(max_length=1, blank=True, null=True)

	def __unicode__(self):
		return u'%s' % (self.charge)

	class Meta:
		verbose_name = "Produkt"
		verbose_name_plural = "Produkte"


class Discount(models.Model):
	discount = models.CharField("Rabatt", max_length=200)
	name = models.CharField("Name", max_length=200)

	def __unicode__(self):
		return str(self.name) + " " + str(self.discount) + "%"

	class Meta:
		verbose_name = "Rabatt"
		verbose_name_plural = "Rabatte"


class Contract(models.Model):
	number = models.CharField("Vertragsnummer", max_length=200)
	products =models.ManyToManyField(Product, blank=True, null=True, related_name='products')
	start_date = models.DateField("Start Date", default=datetime.date.today)
	end_date = models.DateField("End Date", default=datetime.date.today)
	#charge = models.ForeignKey(Charge)
	contact = models.OneToOneField(User,related_name='contract_contact')
	billing_contact = models.OneToOneField(User,related_name='contract_billing_contact')
	#duration = models.ForeignKey(Duration)
	#frequency = models.ForeignKey(Frequency)
	discount = models.ManyToManyField(Discount, blank=True, null=True, related_name='contract_discounts')

	def __unicode__(self):
		return self.number

	def get_frequency_per_week(self):
		return self.type.frequency.frequency / 4

	def calc_price(self):
		x = None

		try:
			x = float(self.type.frequency.frequency) * float(self.type.charge.charge)
		except:
			traceback.print_exc(file=sys.stdout)

		return float(x)

	def get_discounts(self):
		discounts = []
		try:
			x = self.calc_price()

			if x != None:
				for discount in self.discount.all():	
					discount_data = {}
					d = x * (float(discount.discount)/100)
					discount_data["amount"] = float(d)
					discount_data["name"] = discount.name
					discount_data["discount"] = discount.discount
					discounts.append(discount_data)
		except:
			traceback.print_exc(file=sys.stdout)	

		return discounts


	def calc_summ(self):
		summ = None
		registration_fee = 39

		try:
			summ = self.calc_price() + registration_fee
			discounts = self.get_discounts()

			for discount in discounts:
				summ = summ - discount["amount"]
		except:
			traceback.print_exc(file=sys.stdout)	

		return summ
	
	def calc_summ_without_fee(self):
		registration_fee = 39
		summ = self.calc_summ()
		summ = summ - registration_fee

		return summ

	def calc_month_difference(self):
		d1 = self.start_date
		d2 = self.end_date 
		delta = 0

		while True:
			mdays = monthrange(d1.year, d1.month)[1]
			d1 += timedelta(days=mdays)
			if d1 <= d2:
				delta += 1
			else:
				break

		return delta

	class Meta:
		verbose_name = "Vertrag"
		verbose_name_plural = "Verträge"

# Mahnung
class Dun(models.Model):
	level = models.CharField("Mahnlevel", max_length=1, choices=DUN_LEVEL, default=1)


class Invoice(models.Model):
	number = models.CharField("Rechnungsnummer", max_length=200)
	contract = models.OneToOneField(Contract)
	date = models.DateField()
	payed = models.BooleanField()
	dun = models.OneToOneField(Dun)

	def __unicode__(self):
		return (str(self.number) + " " + str(self.person.name))
	
	class Meta:
		verbose_name = "Rechnung"
		verbose_name_plural = "Rechnungen"

class Account(models.Model):
	name = models.CharField("Konto", max_length=200)
	type = models.CharField("Typ", max_length=1, choices=ACCOUNT_TYPE, blank=True, null=True)
	balance = models.DecimalField("Saldo", max_digits=5, decimal_places=2, blank=True, null=True)
	
	def __unicode__(self):
		return (str(self.name) + " " + str(self.balance))
	
class Account_Record(models.Model):
	amount = models.DecimalField("€", max_digits=5, decimal_places=2, blank=True, null=True)
	asset = models.OneToOneField(Account)
	liability = models.OneToOneField(Account)
	date = models.DateField()

	def __unicode__(self):
		return (str(self.liability.name) + " / " + str(self.asset.name) + " " + str(self.amount) + "€")
	

apps/_calendar/models.py
# coding=UTF-8

from django.db import models

from apps._person.models import Person
from apps._accounting.models import Contract
from django.contrib.auth.models import User
import datetime

class Organisation(models.Model):
	name = models.CharField(max_length=200)


class Topic(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Thema"
		verbose_name_plural = "Themen"

class Room(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Raum"
		verbose_name_plural = "Räume"

class Category(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Fach"
		verbose_name_plural = "Fächer"

class Not_At_Event(models.Model):
	excused = models.BooleanField(default=False) # CHANGEND
	comment = models.CharField("Grund", max_length=2000, null=True)  # CHANGEND
	user = models.OneToOneField(Person)

class Event_Comment(models.Model):
	comment = models.CharField("Bewertung", max_length=2000)
	user = models.OneToOneField(Person)

	def __unicode__(self):
		return str(self.user.last_name) + " " + str(self.event.name)

class Event_Grading(models.Model):
	grading = models.CharField("Bewertung", max_length=2000)
	user = models.OneToOneField(Person)

	def __unicode__(self):
		return self.user.username

	class Meta:
		verbose_name = "Bewertung"
		verbose_name_plural = "Bewertungen"

class Event(models.Model):
	name = models.CharField("Name", max_length=200)
	date = models.DateTimeField("Tag", default=datetime.date.today)
	start_time = models.DateTimeField("Beginn", default=datetime.date.today, blank=True, null=True)
	end_time = models.DateTimeField("Ende", default=datetime.date.today, blank=True, null=True)
	room = models.OneToOneField(Room, blank=True, null=True)
	persons = models.ManyToManyField(Person, blank=True, null=True, related_name='user_participants')
	lead = models.OneToOneField(Person, blank=True, null=True,related_name='user_lead')
	category = models.OneToOneField(Category, blank=True, null=True)
	not_at_events = models.OneToOneField(Not_At_Event, blank=True, null=True, related_name='not_at_event')
	event_comments = models.ManyToManyField(Event_Comment, blank=True, null=True, related_name='event_comment')
	event_gradings = models.ManyToManyField(Event_Grading, blank=True, null=True, related_name='event_grading')
	organisation = models.OneToOneField(Organisation)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Stunde"
		verbose_name_plural = "Stunden"
		ordering = ('date', 'start_time', "category")

class Event_Series(models.Model):
	start_date = models.DateTimeField("Beginn", default=datetime.date.today, blank=True, null=True)
	end_date = models.DateTimeField("Ende", default=datetime.date.today, blank=True, null=True)
	events = models.ManyToManyField(Event, blank=True, null=True, related_name='events')

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Stundeserie"
		verbose_name_plural = "Stundeserien"

apps/_person/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

SEX = (
	('m', 'Herr'),
	('f', 'Frau'),
)


class Subject(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Fach"
		verbose_name_plural = "Fächer"

class Grade(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Klasse"
		verbose_name_plural = "Klassen"

class School(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Schule"
		verbose_name_plural = "Schulen"


# TODO find better naming 
class Child_Contact(models.Model):
	grade = models.OneToOneField(Grade, blank=True, null=True) # new
	school = models.OneToOneField(School, blank=True, null=True) # new

	def __unicode__(self):
		return self.child.street

	class Meta:
		verbose_name = "Schüler"
		verbose_name_plural = "Schüler"

class Billing_Type(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Rechnungstyp"
		verbose_name_plural = "Rechnungstypen"

class Billing_Contact(models.Model):
	knr = models.CharField(max_length=200, blank=True, null=True)
	blz = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	billing_type = models.OneToOneField(Billing_Type, blank=True, null=True)

	def __unicode__(self):
		return self.person.user.last_name

	class Meta:
		verbose_name = "Rechnungsadresse"
		verbose_name_plural = "Rechnungsadressen"

class Person(models.Model):
	sex = models.CharField("Geschlecht", max_length=1, choices=SEX, blank=True, null=True)
	birthday = models.DateField("Geburtstag", blank=True, null=True) # new
	street = models.CharField("Strasse", max_length=200, blank=True, null=True)
	hnr = models.CharField("Hausnummer", max_length=10, blank=True, null=True)
	zip = models.IntegerField("PLZ", max_length=8, blank=True, null=True)
	city = models.CharField("Stadt", max_length=200, blank=True, null=True)
	country = models.CharField("Land", max_length=200, blank=True, null=True) # new
	phone = models.CharField("Telefon", max_length=200, blank=True, null=True)
	mobile = models.CharField("Handy", max_length=200, blank=True, null=True)
	accessibility = models.CharField("Mögliche Termine oder Zeiten wo unmöglich gehen.", max_length=600, blank=True, null=True) # new
	user = models.OneToOneField(User)
	child_contact = models.OneToOneField(Child_Contact)
	billing_contact = models.OneToOneField(Billing_Contact)

	def __unicode__(self):
		return str(self.mobile)
	
	def get_user(self):
		return self.user

	class Meta:
		verbose_name = "Benutzer"
		verbose_name_plural = "Benutzer"

apps/_person/views.py
from django.shortcuts import render

# Create your views here.

templates/base/forms/contract.html
{% if contract_form %}
<section id="page">
	<script>
	
		$(document).ready(function() {
			var add_user_buttons = $("#add-new-contact, #add-new-billing-contact");

			add_user_buttons.click(function() {
				var button = $(this);
				var wrapper = $(this).parent();


				button.addClass("hidden");
				wrapper.find(".new-user-form").removeClass("hidden");
				wrapper.find(".user-search").addClass("hidden");

				wrapper.find(".back").click(function() {
					button.removeClass("hidden");
					wrapper.find(".new-user-form").addClass("hidden");
					wrapper.find(".user-search").removeClass("hidden");
				});
			});

			// show contract id if existing
			var contract_id_field = $("#id_number");
			var contract_id = contract_id_field.val();
			if (typeof contract_id != "undefined" && contract_id != "") {
				contract_id_field.parent().prepend(contract_id);
			}

			//show and set billing contact if recently created
			var user_id = $("#id_id").attr("value");
			if (typeof user_id != "undefined" && user_id != "") {
				var select_options = $("#id_billing_contact").find("option");
				select_options.attr('selected', false);
				$.each(select_options, function(key, option) {
					var option = $(option);
					var value = option.val();
					if (value == user_id) {
						var wrapper = option.parent().parent();
						option.attr('selected', true);
						//wrapper.css("display", "block");
						//wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");
						//wrapper.prepend("<label>Rechnungsadresse:</label><input type=\"text\" value=\"" + option.text() + "\"readonly=\"readonly\"/>");

						return false;
					}
				});
			}

			var selected_billing_options = $("#id_billing_contact").find("option:selected");
			show_select_option(selected_billing_options, null, "Vertragspartner", 'id_billing_contact');

			// show contact if set 
			var selected_options = $("#id_contact").find("option:selected");
			show_select_option(selected_options, null, "Schüler", 'id_contact');

			function show_select_option(selected_options, value, label, id) {
				$.each(selected_options, function(key, option) {
					var option = $(option);
					var wrapper = option.parent().parent();
					var text = "";
					var newID = "target_" + id
					var errorDiv = wrapper.find(".error");

					wrapper.css("display", "block");
					wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");

					if (typeof value != "undefined" && value != null && value != "") {
						text = value;
					}
					else {
						if (option.text() != "---------") {
							text = option.text();
							$.cookie(id, text);
						}
					}

					//wrapper.prepend(errorDiv[0].outerHTML + "<label>" + label + ":</label><input id=\"" + newID + "\" type=\"text\" value=\"" + text + "\"readonly=\"readonly\"/>");
				});
			}
		});

	</script>
	<style>
		.right #user-id {
			display: none;
		}
	</style>

	<div>
		<form action="{{ form_action }}" method="post" data-default-action="{{ request.get_full_path }}">
			<section class="two-col">
	
				<div class="left">
					<h3>Schüler</h3>
	
					<div class="user-search">
						<label for="search-user">Benutzer Suchen</label>
						<input type="text" name="search-user" id="add-contract-contact" class="search-user" />
						<div class="results"></div>
					</div>
				</div>
	
				<div class="right">
					<h3>Rechnungskontakt</h3>
					{% if show_new_user %}
						<div class="button" id="add-new-billing-contact">Rechnungskontakt +</div>
	
						<div class="user-search">
							<label for="search-user">Benutzer Suchen</label>
							<input type="text" name="search-user" id="add-contract-billing-contact" class="search-user" />
							<div class="results"></div>
						</div>
	
						<div class="hidden new-user-form">
							<div class="button back">zurück zur Benutzersuche</div>
							{% include 'base/forms/person_for_contract.html' %}
						</div>
					{% else %}
						{% include 'base/forms/person_for_contract.html' %}
					{% endif %}
				</div>
			</section>

			<div style="margin: 0 0 0 0; width: 100%;">
				<h3>Vertragsdaten</h3>
				<div class="form-field">
					{% csrf_token %}
				</div>
				{% for field in contract_form %}
					<div class="form-field">
						{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
						<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
						{{ field }}
					</div>
				{% endfor %}
				<div class="form-field">
					<input class="button" type="submit" value="Speichern" />
				</div>
			</div>

			<div class="user-search-values hidden">
				{% for user in all_users %}
					<div data-cat="{% for category in user.category.all %}{{ category.name }}{% endfor %}" data-id="{{ user.pk }}" class="search-value user button" data-name="{{ user.first_name }} {{ user.last_name }}">
						{{ user.first_name }} {{ user.last_name }}
					</div>
				{% endfor %}
			</div>
		</form>
	</div>
{% else %}
	<h1>nope</h1>
{% endif %}
</section>

templates/base/forms/edit_group.html
<div id="content">
	{% if info %}
		<h2>{{ info }}</h2>
	{% endif %}

	{% if group_form %}
	<br/><br/><br/>
		<div>
			<form action="./" method="post" data-default-action="{{ request.get_full_path }}">
				{% csrf_token %}
				{{ group_form.as_p }}
				<input class="button" type="submit" value="Speichern" />
			</form>
		</div>
	
	{% endif %}
		{% if form %}
			<form action="./" method="post" data-default-action="{{ request.get_full_path }}">
		{% csrf_token %}
	    {{ form.non_field_errors }}
	    <div class="form-field">
	        {{ form.name.errors }}
	        <label for="id_name">Name <br/> Beschreibung</label>
	        {{ form.name }}
	    </div>
		<div class="form-field">
			{{ form.date.errors }}
			<label for="id_date">Datum:</label>
			{{ form.date }}
		</div>
	    <div class="form-field">
	        {{ form.start_time.errors }}
	        <label for="id_start_time">Beginn:</label>
	        {{ form.start_time }}
	    </div>
		<div class="form-field">
			{{ form.end_time.errors }}
			<label for="id_end_time">Ende:</label>
			{{ form.end_time }}
		</div>
		<div class="form-field">
			{{ form.room.errors }}
			<label for="id_room">Raum:</label>
			{{ form.room }}
		</div>
	
		<div class="form-field">
				<div class="search">
					<input class="trigger-search" type="text" value="Suche" style="padding: 3px;" autocomplete="off" />
					<div class="search-results"></div>
					<div class="search-values">
						{% for instance in form.users.field.queryset %}
							<div data-cat="employee" data-id="{{ instance.pk }}" draggable="true" class="search-value user button">
								<span class="text">{{ instance.first_name }} {{ instance.last_name }}</span>
							</div>
						{% endfor %}
					</div>
				</div>
			<label for="id_persons">Schüler:</label>
			{{ form.users }}
		</div>
		<div class="form-field">
			{{ form.category.errors }}
			<label for="id_category">Fach:</label>
			{{ form.category }}
		</div>
		
		<div class="form-field">
			{{ form.lead.errors }}
			<label for="id_lead">Lehrer:</label>
			{{ form.lead }}
		</div>
		
		<p><input class="button" type="submit" value="Absenden" /></p>
	</form>
	{% endif %}
</div>

templates/base/forms/event.html
<div id="content">
<div id="event-form-wrapper" >
	<form id="event-form" action="./" method="post" data-callback="Calendar_View.newEventFormCallback()" data-default-action="{{ request.get_full_path }}">
		{% csrf_token %}

		<div class="form-field" style="display: none;">
			{{ form.non_field_errors }}
			{{ form.name.errors }}
			<label for="id_name">Name <br/> Beschreibung</label>
			{{ form.name }}
		</div>
		<div class="form-field">
			{{ form.date.errors }}
			<label for="id_date">Datum:</label>
			{{ form.date }}
		</div>
		<div class="form-field">
			{{ form.start_time.errors }}
			<label for="id_start_time">Beginn:</label>
			{{ form.start_time }}
		</div>
		<div class="form-field">
			{{ form.end_time.errors }}
			<label for="id_end_time">Ende:</label>
			{{ form.end_time }}
		</div>
		<div class="form-field">
			{{ form.room.errors }}
			<label for="id_room">Raum:</label>
			{{ form.room }}
		</div>
		<div class="form-field">
			<div class="search">
				<input class="trigger-search" type="text" value="Suche" style="padding: 3px;" autocomplete="off" />
				<div class="search-results"></div>
				<div class="search-values">
					{% for instance in form.users.field.queryset %}
						<div data-cat="employee" data-id="{{ instance.pk }}" draggable="true" class="search-value user button">
							<span class="text">{{ instance.first_name }} {{ instance.last_name }}</span>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="form-field">
			{{ form.users.errors }}
			<label for="id_users">Schüler:</label>
			<div>
			{{form.users}}
			</div>
	
		</div>
		<div class="form-field">
			{{ form.category.errors }}
			<label for="id_category">Fach:</label>
			{{ form.category }}
		</div>
		<div class="form-field">
			{{ form.lead.errors }}
			<label for="id_lead">Lehrer:</label>
			{{ form.lead }}
		</div>
		<div class="form-field">
			{{ form.event_group.errors }}
			<div class="hidden">{{ form.event_group }}</div>
			<label for="id_event_group">Termin Serie:
			</label>
			<!-- 
			<a id="edit-event-group" class="button" href="/edit/event_group/{% if form.initial.id %}{{ form.initial.id }}{% else %}new{% endif %}/{% if form.event_group.value %}{{ form.event_group.value }}{% else %}new{% endif %}/">
				<img src="/media/img/edit.png" alt="edit"/>
			</a>
			-->
			<a id="new-event-group" class="button" href="/add/event_group/{% if form.initial.id %}{{ form.initial.id }}{% else %}new{% endif %}/">
				<strong>neu</strong>
			</a>
		</div>
		<div class="form-field">
			<input class="button" type="submit" value="Absenden" />
		</div>
	</form>
</div>
</div>

templates/base/forms/event_group.html
<div>	
	<script>
		$("document").ready(function() {
			var label = null;
			var value = null;

			var start_date = $("#id_start_date");
			label = start_date.parent().find("label");
			value = "{{ start_date | date:'d.m.Y' }}";
			label.text(label.text() + " " + value);

			var end_date = $("#id_end_date");
			label = end_date.parent().find("label");
			value = "{{ end_date | date:'d.m.Y' }}";
			label.text(label.text() + " " + value);

// 			$("#edit-event-form").submit(function(e) {
// 				var input_end_date = $("#id_end_date");
// 				console.log("input_end_date ", input_end_date);
// 				console.log("input_end_date.attr value " , input_end_date.attr("value"));
// 				if (typeof input_end_date == "undefined" || input_end_date.attr("value") == "" || input_end_date.attr("value") == " ") {
// 					e.preventDefault();
// 					input_end_date.addClass("error");

// 					return false;
// 				}
// 			});
		});
	</script>
	<form id="edit-event-form" action="./" method="post">
		{% csrf_token %}

		{% if form %}
			{% for field in form %}
				<div class="form-field {{ field.label }}">
					{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
					<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
					{{ field }}
				</div>
			{% endfor %}

			<div class="form-field">
				<input class="button" type="submit" value="Speichern" />
			</div>
		{% else %}
			<a href="javascript:history.back()" class="button">zurück</a>
		{% endif %}
	</form>
</div>

templates/base/forms/person_for_contract.html
{% if form_user %}
	<div class="form-field">
	{{form_user.id}}
	</div>
	<div class="form-field">
		{% for pk, group in form_user.groups.field.widget.choices %}
			<label for="id_group_{{ pk }}" class="button">
				<input {% for group in selected_groups.all %}{% if group.pk == pk %}checked="checked"{% endif %}{% endfor %} type="checkbox" id="id_group_{{ pk }}" value="{{ pk }}" name="groups" />
				<span>{{group}}</span>
			</label>	
		{% endfor %}
	</div>

	<div class="form-field">
		{{ form_user.username.errors }}
		<label for="id_lead">Benutzername:</label>
		{{ form_user.username }}
	</div>
	<div class="form-field">
		{{ form_user.first_name.errors }}
		<label for="id_lead">Vorname:</label>
		{{ form_user.first_name }}
	</div>
	<div class="form-field">
		{{ form_user.last_name.errors }}
		<label for="id_lead">Nachname:</label>
		{{ form_user.last_name }}
	</div>
	<div class="form-field">
		{{ form_user.email.errors }}
		<label for="id_field">E-Mail:</label>
		{{ form_user.email }}
	</div>
{% endif %}
{% if form_person %}
	{% for field in form_person %}
		<div class="form-field">
			{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
			<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
			{{ field }}
		</div>
	{% endfor %}
{% endif %}

templates/base/forms/standard_form.html
<div id="content">
{% if form %}
	<div id="standard-form">
		{% if info %}
			<h2>{{ info }}</h2>
		{% endif %}
		<script>
			$(document).ready(function() {
				var user = $("#id_user");
				var event = $("#id_event");
				user.hide();
				event.hide();
				console.log("event.parent().find ", event.parent().find("label"));
				user.parent().find("label").html("<b>Schüler:</b> " + user.find(":selected").text());
				event.parent().find("label").html("<b>Stunde:</b> " + event.find(":selected").text());
			});
		</script>
		<div>	
			<form action="./" id="" method="post" data-default-action="{{ request.get_full_path }}">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-field {{ field.label | lower }}">
						{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
						<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
						{{ field }}
					</div>
				{% endfor %}
				<div class="form-field">
					<input class="button" type="submit" value="Speichern" />
				</div>
			</form>
		</div>
	</div>
{% endif %}
</div>

templates/base/forms/user_comment.html
{% if form %}
	<div id="comment-form">	
		<form action="./" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input class="button" type="submit" value="Speichern" />
		</form>
	</div>
{% endif %}